"""Lexicon de aspecte pentru review-uri de fitness trackers (română)."""

ASPECT_CATEGORIES = {
    "Design și confort": [
        "design",
        "confortabil",
        "confort",
        "brățar",
        "bratara",
        "material",
        "ușor de purtat",
        "usor de purtat",
        "incomod",
        "premium",
    ],
    "Display / Ecran": [
        "display",
        "ecran",
    ],
    "Baterie și autonomie": [
        "baterie",
        "autonomie",
        "încărc",
        "incarc",
        "ține bine",
        "tine bine",
    ],
    "Aplicație și interfață": [
        "aplicați",
        "aplicatie",
        "interfață",
        "interfata",
        "interfața",
        "interfata",
        "îmbunătățiri",
        "imbunatatiri",
    ],
    "Conectivitate și sincronizare": [
        "sincroniz",
        "bluetooth",
        "conectiv",
        "deconect",
        "telefon",
    ],
    "Monitorizare și senzori": [
        "monitoriz",
        "senzor",
        "somn",
        "activit",
        "fitness",
        "antrenament",
    ],
    "Notificări": [
        "notific",
    ],
    "Preț / calitate-preț": [
        "preț",
        "pret",
        "calitate-preț",
        "calitate pret",
        "raport",
    ],
    "Performanță": [
        "performan",
        "răspunde rapid",
        "raspunde rapid",
        "vitez",
    ],
    "Funcționalitate generală": [
        "funcți",
        "functi",
        "specificați",
        "specificatii",
        "utilizare",
        "experiență",
        "experienta",
    ],
    "Rezistență și impermeabilitate": [
        "impermeab",
        "rezisten",
        "ip68",
        "ip67",
        "apă",
        "apa",
        "înot",
        "inot",
        "duș",
        "dus",
        "waterproof",
    ],
    "Compatibilitate dispozitive": [
        "compatibil",
        "android",
        "ios",
        "iphone",
        "samsung",
        "huawei",
        "sistem de operare",
    ],
    "GPS și localizare": [
        "gps",
        "localiz",
        "traseu",
        "hartă",
        "harta",
        "distanță",
        "distanta",
        "parcurs",
    ],
    "Ușurință în utilizare": [
        "ușor de folosit",
        "usor de folosit",
        "simplu de utilizat",
        "începători",
        "incepatori",
        "utilizatori noi",
        "complicat",
        "greu de folosit",
    ],
}

REVIEW_COLUMNS = [
    "Reviewuri Pozitive",
    "Reviewuri Negative",
    "Reviewuri Neutre",
    "Reviewuri Mixte",
]

ASPECT_OUTPUT_COLUMNS = [
    "Aspecte_Pozitive",
    "Aspecte_Negative",
    "Aspecte_Neutre",
    "Aspecte_Mixte",
    "Aspecte_Identificate",
]
