"""Lexicon de aspecte pentru review-uri de fitness trackers (română)."""

# Versiune vizibilă în UI — creșteți la fiecare modificare a lexiconului
LEXICON_VERSION = "2026.06.03"

ASPECT_CATEGORIES = {
    "Design și confort": [
        "design",
        "atractiv",
        "atractivă",
        "atractiva",
        "confortabil",
        "confort",
        "brățar",
        "bratara",
        "material premium",
        "material confortabil",
        "ușor de purtat",
        "usor de purtat",
        "incomod",
        "premium",
    ],
    "Display / Ecran": [
        "display",
        "ecran",
        "amoled",
    ],
    "Baterie și autonomie": [
        "baterie",
        "autonomie",
        "încărc",
        "incarc",
        "ține bine",
        "tine bine",
    ],
    "Aplicație și interfață": [
        "aplicați",
        "aplicatie",
        "interfață",
        "interfata",
        "interfața",
        "interfata",
        "îmbunătățiri",
        "imbunatatiri",
    ],
    "Conectivitate și sincronizare": [
        "sincroniz",
        "bluetooth",
        "conectiv",
        "deconect",
        "telefon",
    ],
    "Monitorizare și senzori": [
        "monitoriz",
        "senzor",
        "somn",
        "activit",
        "fitness",
        "antrenament",
    ],
    "Notificări": [
        "notific",
    ],
    "Preț / calitate-preț": [
        "preț",
        "pret",
        "calitate-preț",
        "calitate pret",
        "raport",
    ],
    "Calitate construcție și materiale": [
        "calitate material",
        "calitatea materialului",
        "calitatea produsului",
        "materialului",
        "material slab",
        "material bun",
        "material de calitate",
        "finisaj",
        "construcție",
        "constructie",
        "calitate slabă",
        "calitate slaba",
        "calitate bună",
        "calitate buna",
    ],
    "Livrare și logistică": [
        "livrare",
        "livră",
        "livrata",
        "livrat",
        "livrarea",
        "curier",
        "expediere",
        "ambalaj",
        "transport",
        "colet",
        "a ajuns repede",
        "a ajuns rapid",
    ],
    "Performanță": [
        "performan",
        "perfomanta",
        "perfomant",
        "răspunde rapid",
        "raspunde rapid",
        "vitez",
    ],
    "Funcționalitate generală": [
        "funcți",
        "functi",
        "specificați",
        "specificatii",
        "utilizare",
        "experiență",
        "experienta",
    ],
    "Rezistență și impermeabilitate": [
        "impermeab",
        "rezisten",
        "ip68",
        "ip67",
        "apă",
        "apa",
        "înot",
        "inot",
        "duș",
        "dus",
        "waterproof",
    ],
    "Compatibilitate dispozitive": [
        "compatibil",
        "android",
        "ios",
        "iphone",
        "samsung",
        "huawei",
        "sistem de operare",
    ],
    "GPS și localizare": [
        "gps",
        "localiz",
        "traseu",
        "hartă",
        "harta",
        "distanță",
        "distanta",
        "parcurs",
    ],
    "Ușurință în utilizare": [
        "ușor de folosit",
        "usor de folosit",
        "simplu de utilizat",
        "începători",
        "incepatori",
        "utilizatori noi",
    ],
}

REVIEW_COLUMNS = [
    "Reviewuri Pozitive",
    "Reviewuri Negative",
    "Reviewuri Neutre",
    "Reviewuri Mixte",
]

ASPECT_OUTPUT_COLUMNS = [
    "Aspecte_Pozitive",
    "Aspecte_Negative",
    "Aspecte_Neutre",
    "Aspecte_Mixte",
    "Aspecte_Identificate",
]

SENTIMENT_BUCKETS = ("pozitive", "negative", "neutre", "mixte")

REVIEW_TONE_TO_BUCKET = {
    "pozitiv": "pozitive",
    "negativ": "negative",
    "neutru": "neutre",
    "mixt": "mixte",
}

# Ton per aspect — fără bucket „mixte” (mixt e doar la nivel de review)
ASPECT_TONE_TO_BUCKET = {
    "pozitiv": "pozitive",
    "negativ": "negative",
    "neutru": "neutre",
}

SENTIMENT_POSITIVE = [
    "excelent",
    "excelentă",
    "excelenta",
    "foarte bun",
    "foarte buna",
    "bună",
    "buna",
    "bun ",
    "util",
    "utile",
    "precis",
    "precisă",
    "precisa",
    "rapid",
    "rapidă",
    "rapida",
    "clar",
    "clară",
    "clara",
    "mare",
    "exactă",
    "exacta",
    "exact",
    "autonomie mare",
    "monitorizare exact",
    "recomand",
    "mulțumit",
    "multumit",
    "satisfăcut",
    "satisfacut",
    "perfect",
    "minunat",
    "minunată",
    "minunata",
    "super",
    "ușor de folosit",
    "usor de folosit",
    "confortabil",
    "premium",
    "intuitiv",
    "intuitivă",
    "intuitiva",
    "ușor de purtat",
    "usor de purtat",
    "atractiv",
    "atractivă",
    "atractiva",
    "amoled",
]

NEGATION_PHRASES = [
    "nu par",
    "nu sunt",
    "nu e ",
    "nu e,",
    "nu este",
    "nu prea",
    "nu foarte",
    "nu-i ",
    "nu i ",
    "fara ",
    "fără ",
    "nu ",
]

SENTIMENT_NEGATIVE = [
    "prost",
    "proastă",
    "proasta",
    "slab",
    "slabă",
    "slaba",
    "rău",
    "rau",
    "lent",
    "lentă",
    "lenta",
    "incomod",
    "dezamăg",
    "dezamag",
    "problem",
    "defect",
    "nu funcționeaz",
    "nu functioneaz",
    "nu merge",
    "nu recomand",
    "deloc",
    "greu de folosit",
    "complicat",
    "întârz",
    "intarz",
    "întârziere",
    "intarziere",
    "delay",
    "delay mare",
    "cu delay",
    "deconect",
    "durere",
    "nesatisfăc",
    "nesatisfac",
    "ridicat",
    "ridicată",
    "ridicata",
    "scump",
    "scumpă",
    "scumpa",
    "prea scump",
    "scăzut",
    "scazut",
    "scăzută",
    "scazuta",
    "scăzuta",
    "cam scazut",
    "cam scăzut",
    "slab perform",
    "performanță slabă",
    "performanta slaba",
    "cam slab",
    "nu prea bun",
    "sub așteptări",
    "sub asteptari",
    "mai mică",
    "mai mica",
    "mai mic decât",
    "mai mic decat",
    "mai puțin decât",
    "mai putin decat",
    "decât promis",
    "decat promis",
    "cea promisă",
    "cea promisa",
    "nu ține cât",
    "nu tine cat",
    "sub promisiuni",
    "poate varia",
    "poate fluctua",
    "tinde să varieze",
    "tinde sa varieze",
    "imprecis",
    "inexact",
    "inexactă",
    "inexacta",
    "nu e constant",
    "nu este constant",
    "precizie slabă",
    "precizie slaba",
    "slabă precizie",
    "slaba precizie",
    "necesită îmbunătăț",
    "necesita imbunatat",
    "necesită",
    "necesita",
    "cere îmbunătăț",
    "lipsuri",
    "de îmbunătățit",
    "de imbunatatit",
]

SENTIMENT_NEUTRAL = [
    "normal",
    "mediu",
    "medie",
    "decent",
    "decentă",
    "decenta",
    "acceptabil",
    "standard",
    "obișnuit",
    "obisnuit",
    "suficient",
    "în medie",
    "in medie",
    "ok",
]

MIXED_MARKERS = [
    "însă",
    "insa",
    "dar ",
    "totuși",
    "totusi",
    "totodată",
    "totodata",
    "cu toate acestea",
    "pe de altă parte",
    "pe de alta parte",
    "în schimb",
    "in schimb",
    "însă ",
]
